// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SchemaMigration struct {
	Version string
}

type User struct {
	ID           int64
	Username     string
	PasswordHash pgtype.Text
}
