// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SchemaMigration struct {
	Version string
}

type Session struct {
	Key        string
	Data       []byte
	ExpiryDate pgtype.Timestamp
}

type User struct {
	ID           int64
	PasswordHash pgtype.Text
	LastLogin    pgtype.Timestamp
	IsActive     pgtype.Bool
	Username     string
	Email        pgtype.Text
	FirstName    pgtype.Text
	LastName     pgtype.Text
	DateJoined   pgtype.Timestamp
}
