// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package orm

import (
	"context"
)

const createUser = `-- name: CreateUser :one
;

INSERT INTO users (id) VALUES (?) RETURNING id
`

func (q *Queries) CreateUser(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, createUser, id)
	err := row.Scan(&id)
	return id, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id FROM users WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	err := row.Scan(&id)
	return id, err
}

const listUsers = `-- name: ListUsers :many
SELECT id FROM users ORDER BY id
`

func (q *Queries) ListUsers(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
;


DELETE FROM users WHERE id = ?
`

// UPDATE users SET * where id = ?;
func (q *Queries) UpdateUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateUser, id)
	return err
}
