// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users ( password_hash, username, email, first_name, last_name, date_joined )
VALUES ( $1, $2, $3, $4, $5, $6 )
RETURNING ( username, email, first_name, last_name )
`

type CreateUserParams struct {
	PasswordHash pgtype.Text
	Username     string
	Email        pgtype.Text
	FirstName    pgtype.Text
	LastName     pgtype.Text
	DateJoined   pgtype.Timestamp
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.PasswordHash,
		arg.Username,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.DateJoined,
	)
	var column_1 interface{}
	err := row.Scan(&column_1)
	return column_1, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, password_hash, last_login, is_active, username, email, first_name, last_name, date_joined FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PasswordHash,
		&i.LastLogin,
		&i.IsActive,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.DateJoined,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, password_hash, last_login, is_active, username, email, first_name, last_name, date_joined FROM users
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.PasswordHash,
			&i.LastLogin,
			&i.IsActive,
			&i.Username,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.DateJoined,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
